os: osx

before_install:
  # - brew install yarn
install:
  - brew install hugo
script:
  - hugo new site myblog
  - mkdir myblog/content/posts
  - cd myblog/content
  - git clone https://${GH_REF}/blog-backup.git
  - mv blog-backup posts
  - cd ..
  - rm -rf config.toml
  - wget https://raw.githubusercontent.com/uncoder-fe/blog-backup/master/config.toml
  - cd themes/
  - git clone https://github.com/budparr/gohugo-theme-ananke.git
  - cd ..
  - hugo
  # - tree -L 3
after_script:
  - cd ./public
  - git init
  - git config user.name "uncoder-fe"
  - git config user.email "uncoder@qq.com"
  - git add .
  - git commit -m "Update by Travis CI"
  - git push --force --quiet "https://${CLI_TOKEN}@${GH_REF}/uncoder-fe.github.io.git" master:master
branches:
  only:
    - master
env:
  global:
    - GH_REF: github.com/uncoder-fe